---
# Ejecuta instalación/verificación del Zabbix Agent 2 y genera reporte local
- name: Verificar e instalar Zabbix Agent 2 desde repositorio HTTP local
  hosts: ktuno-nuevo
  become: true


  tasks:
    - name: Ejecutar solo la auditoría del rol zabbix_agent2
      ansible.builtin.include_role:
        name: zabbix_agent2
        tasks_from: Deploy_ZabbixAgent2.yml


# ==== PLAY 2: Compilar reporte y generar Excel ====
- name: Compilar reporte y generar Excel
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Asegurar directorio de salidas
      ansible.builtin.file:
        path: "{{ playbook_dir }}/Salidas_Playbooks"
        state: directory
        mode: '0755'

    - name: Exportar JSON con resultados
      ansible.builtin.copy:
        content: "{{ hostvars | json_query(query) | to_nice_json }}"
        dest: "{{ playbook_dir }}/Salidas_Playbooks/zabbix_auditoria.json"
        mode: '0644'
      vars:
        query: "*[].resultados_zabbix[]"
      run_once: true

    - name: Ejecutar script Python para generar Excel
      ansible.builtin.command: python3 scripts/export_deploy_agent2_excel.py
      args:
        chdir: "{{ playbook_dir }}"
      run_once: true
      changed_when: false
