---
- name: 0# Eliminar usuarios por zona
  hosts: inventario
  become: true

  # 0.1# Zona seleccionada (se debe pasar SIEMPRE con -e "zona=...")
  vars:
    zona: "{{ zona }}"
    grupo_base: "soporte"

  pre_tasks:
    # 1# Validar que exista el archivo de variables de la zona en el controlador
    - name: 1# Validar que exista el archivo de variables de la zona (en el controlador)
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/vars/usuarios_{{ zona }}.yml"
      register: zona_vars_file
      delegate_to: localhost
      run_once: true

    # 1.1# Mostrar resultado del stat para depuración
    - name: 1.1# Debug resultado del stat
      ansible.builtin.debug:
        var: zona_vars_file
      delegate_to: localhost
      run_once: true

    # 2# Fallar si el archivo no existe
    - name: 2# Fallar si no existe el archivo de variables para la zona
      ansible.builtin.fail:
        msg: "No existe {{ playbook_dir }}/vars/usuarios_{{ zona }}.yml. Crea el archivo o cambia la zona con -e 'zona=...'."
      when: not zona_vars_file.stat.exists
      delegate_to: localhost
      run_once: true

    # 3# Incluir archivo de variables de la zona
    - name: 3# Incluir variables de la zona (lista 'usuarios')
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/usuarios_{{ zona }}.yml"
      delegate_to: localhost
      run_once: true

  tasks:
    # 4# Eliminar usuarios de la zona seleccionada
    - name: 4# Eliminar usuarios de {{ zona }}
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent
        remove: true         # elimina también home y mail spool
      loop: "{{ usuarios }}"
      loop_control:
        label: "{{ item.name }}"
      tags: [usuarios, eliminar]

    # 5# (Opcional) Eliminar grupo si ya no quedan usuarios
    - name: 5# Eliminar grupo '{{ grupo_base }}' si ya no se usa
      ansible.builtin.group:
        name: "{{ grupo_base }}"
        state: absent
      ignore_errors: true   # por si el grupo aún es usado por otros
      tags: [grupo, eliminar]
