[oracle]
CKPR1 ansible_host=172.25.87.110
CKPR2 ansible_host=172.25.87.120
WMS1 ansible_host=192.168.97.53
WMS2 ansible_host=192.168.97.54
CKPRU1 ansible_host=172.25.77.107
ALKANA1 ansible_host=192.168.97.45
ALKANA2 ansible_host=192.168.97.46
GSPSPEC ansible_host=10.181.3.156
OIM ansible_host=10.181.3.79

[mysql]
CORBEMOVIL ansible_host=10.181.0.21
MOVILTRACK ansible_host=10.181.3.109
MERCADERISTAS ansible_host=10.181.3.23
DESPACHOS-DIGI ansible_host=10.181.4.244

[linux:children]
oracle
mysql

[all:vars]
#ansible_user=usuario_ansible
ansible_become=true