- name: Verificar colecciones instaladas en el entorno de ejecución
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar lista de colecciones instaladas
      ansible.builtin.command: ansible-galaxy collection list
      register: resultado
      changed_when: false

    - name: Mostrar salida
      ansible.builtin.debug:
        var: resultado.stdout_lines

