---
- name: Playbook de prueba para tux con sudo
  hosts: 10.181.6.38
  become: true
  become_user: hola  # Escala de privilegios como tux
  tasks:
    - name: Verificar el usuario actual (escalado con sudo)
      ansible.builtin.command:
        cmd: whoami
      register: whoami_output
      changed_when: false

    - name: Mostrar el usuario escalado
      ansible.builtin.debug:
        msg: "El usuario actual escalado es: {{ whoami_output.stdout }}"
