---
- name: Tarea para Crear Relación de Confianza SSH con llaves privadas
  hosts: LOTE1-General
  become: true

  tasks:

    ## Crear Usuarios de Ansible
    - name: Crear usuarios Ansible (iacolcoauto y ansible_test)
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        create_home: true
        groups: wheel
      loop:
        - iacolcoauto
        - ansible_test

    ## Permitir SUDO sin contraseña -- Requerido en Ansible
    - name: Permitir sudo sin contraseña a usuarios Ansible
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ item }}"
        line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
        create: true
        owner: root
        group: root
        mode: '0440'
        validate: visudo -cf %s
      loop:
        - iacolcoauto
        - ansible_test

    ## Crear directorio .ssh para usuarios Ansible
    - name: Crear directorio .ssh para usuarios Ansible
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{ item }}"
        mode: '0700'
      loop:
        - iacolcoauto
        - ansible_test

    ## Agregar claves públicas SSH a usuarios Ansible
    - name: Agregar claves públicas SSH a usuarios Ansible
      ansible.builtin.copy:
        dest: "/home/{{ item.user }}/.ssh/authorized_keys"
        content: "{{ item.key }}"
        owner: "{{ item.user }}"
        mode: '0600'
      loop:
        - { user: "iacolcoauto", key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3NzBHvokb0EmAMlqgXVgUMYBlsVVjM6e28dzqhW7ykRfjrjEx4jV+0H3I/yvPqIga/iBUmg3CKBnL9rm1+9vW7f5B2JiCH0tPAJAfLDZ7As7KHuL3TeV5VTGursQ7HgU2fWVfoqP/yzGsrCxdQizTlDd9QpB8skqjXIf9nIV+CZJqEHxy0/EHXdm/KuBZbBd+7u/3ZxVMU7zTfJMC48ZV0Et8eu5pzn3mCJjETpfULrnBIoPoJ8otcX19xfygEcuF8Iv6eqnjoRoIEcDhQZi/ayTKiTz7Ezjf1idpBois+iwGlSkLCQ4j6Y2cRYyI/b+fVPnUq+89i2si4/J2J6yt10I3heO6iWvNFi0hgloyMegZiQtnWUyLfay1s7FYtmw6HV4cvJX215j66ETURpSIeg1vFqqf6BO2DxHampjjVfBrGyKuuWXqMiKiLMrM7CVzkOoX3PevPL+rdOU85M/lhNFAY/ioblqjea1kjVYxn/7iLGvWcjbp60MMVGVAEGkn2WubLbAh2xZYS0RFG1lrpBTtb1Alu6CN4kx2zfFhLbIEAM/2WKOWSZMo7CH0ynUbzlNKkuImDuAdxIZaluHPjQ0YCYs5I4rOKFm1ixes16zk25vQnZQ2kfEI4WhAnI1D1M7GmmHbkRAFlxpReDG9JwykHuQSPzld5pqGJoQH1Q== iacolcoauto@ansibleawx" }
        - { user: "ansible_test", key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPW8I6d7AAAkfrObeWMBdayjEHP9pzCfR5/KGVNkq4nBCK2Sb7dohPLsateMZfaQD0DCBI7YJDrKUw4P9ZOCXbM= root@Ansible" }
