---
- name: Tarea para recolectar uptime BIA
  hosts: 10.181.0.155
  become: false
  gather_facts: true

  vars:
    csv_path: '/ansible/Salidas-Ansible/Salida_Uptime/'
    csv_filename: 'BIA_UPTIME.csv'

  tasks:
    - name: Create CSV directory if it doesn't exist
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ csv_path }}"
        state: directory

    - name: Write uptime into CSV
      delegate_to: localhost
      ansible.builtin.lineinfile:
        dest: "{{ csv_path }}/{{ csv_filename }}"
        line: "{{ inventory_hostname }},{{ ansible_hostname }},{{ (ansible_facts.uptime_seconds / 86400) | int }}"
        create: true
        state: present
