---
- name: Tarea para recolectar uptime BIA
  hosts: 10.181.0.155
  become: false
  gather_facts: true

  vars:
    csv_path: '/tmp'
    csv_filename: 'BIA_UPTIME.csv'

  tasks:
    - name: Write uptime into CSV on localhost
      local_action:
        module: lineinfile
        path: "{{ csv_path }}/{{ csv_filename }}"
        line: "{{ inventory_hostname }},{{ ansible_hostname }},{{ (ansible_facts.uptime_seconds / 86400) | int }}"
        create: true
        state: present
      run_once: true

