---
- name: Tarea para recolectar uptime BIA
  hosts: 10.181.0.155
  become: false
  gather_facts: true

  vars:
    temp_file: /tmp/uptime_{{ inventory_hostname }}.txt
    local_path: '/ansible/Salidas-Ansible/Salida_Uptime/Salida_Uptime_BIA'

  tasks:
    - name: Generate uptime data on the host
      copy:
        dest: "{{ temp_file }}"
        content: "{{ inventory_hostname }},{{ ansible_hostname }},{{ (ansible_facts.uptime_seconds / 86400) | int }}"

    - name: Fetch uptime data to local path
      delegate_to: localhost
      fetch:
        src: "{{ temp_file }}"
        dest: "{{ local_path }}/"
        flat: yes

    - name: Remove temporary file from remote host
      file:
        path: "{{ temp_file }}"
        state: absent
