---
- name: Despliegue y validación Nessus Agent
  hosts: ak170-backup
  gather_facts: true
  become: true

  tasks:
    - name: Ejecutar deploy de Nessus Agent
      ansible.builtin.import_role:
        name: nessus_agent
        tasks_from: deploy.yml
