---
- name: Despliegue unificado de agentes (Trendmicro / Zabbix / Nessus)
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: true

  pre_tasks:
    - name: Mostrar selección de instalación
      debug:
        msg:
          - "Instalar Trendmicro: {{ install_trendmicro | default(false) }}"
          - "Instalar Zabbix:     {{ install_zabbix | default(false) }}"
          - "Instalar Nessus:     {{ install_nessus | default(false) }}"

    - name: Validar que al menos un agente fue seleccionado
      fail:
        msg: "No seleccionaste ningún agente. Marca al menos uno en la encuesta (Survey)."
      when:
        - not (install_trendmicro | default(false) | bool)
        - not (install_zabbix | default(false) | bool)
        - not (install_nessus | default(false) | bool)

  roles:
    - role: trendmicro
      when: install_trendmicro | default(false) | bool

    - role: zabbix_agent2
      when: install_zabbix | default(false) | bool

    - role: nessus_agent
      when: install_nessus | default(false) | bool
