---
# Variables por defecto
nessus_force_reinstall: true
nessus_manager_host: "10.181.8.192"
nessus_manager_port: 8834
nessus_agent_key: "279fa0cfb3549180f65cffe7a095455a4ba825af6ed6ad923cb7f228870a1694"
nessus_agent_groups: "corbeta" ## opcional
nessus_try_link: true
nessus_force_relink: false
nessus_cli_path: "/opt/nessus_agent/sbin/nessuscli"


# Carpeta de instaladores (relativa a la raíz del proyecto/playbook_dir)
nessus_installers_dir: "{{ playbook_dir | realpath }}/installers"

# Carpeta de salidas (en el controlador)
nessus_output_dir: "{{ playbook_dir | realpath }}/Salidas_Playbooks"

# Mapa de selección por SO
nessus_pkg_dir_map:
  RedHat-7: "rhel7"
  RedHat-8: "rhel8"
  RedHat-9: "rhel9"
  OracleLinux-7: "rhel7"
  OracleLinux-8: "rhel8"
  OracleLinux-9: "rhel9"
  Suse-12: "sles12"
  Suse-15: "sles15"
  Debian-any: "debian"
  Ubuntu-any: "ubuntu"
  Fedora-any: "fedora"
  Amazon-any: "amazon"

# Ruta remota del instalador
nessus_installer_dest_dir: "{{ ansible_env.HOME }}"
