
## inventario Relacion de Confianza #####




### INVENTARIO ######

######## Servidores PPU ###########

[prueba]
#alflo-n3    ansible_host=10.185.0.60
#TESTSEGULBBOGDIS01  ansible_host=10.181.8.209
suse15-sp5-sp7  ansible_host=10.181.8.36


