
## inventario Relacion de Confianza #####




### INVENTARIO ######

######## Servidores PPU ###########

[prueba]
#olharde ansible_host=10.181.11.61 ansible_user=tux
#rhharde ansible_host=10.181.11.60 ansible_user=tux
#susetestharde ansible_host=10.181.11.62
#akper-n1 ansible_host=172.16.9.3
#crmtestmicros ansible_host=10.181.11.192 ansible_user=tux
#mantis-qa ansible_host=10.181.11.151 ansible_user=tux
alka1-n0 ansible_host=10.206.42.6
alkau-n0 ansible_host=10.181.5.69
