---
- name: Notificar inicio de reinicio JDA AKT NODO3
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Enviar notificación inicial a Teams
      ansible.builtin.uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        body_format: json
        body:
          text: "Se inicia el reinicio del {{ nodo }} de {{ ambiente }} en Windows y Linux. Por favor tener presente la ventana de intervención."
        status_code:
          - 200
          - 202