---
- name: Auditoria curl/libcurl + Generacion Excel (VERSION AFECTADA SI/NO)
  hosts: all
  gather_facts: true
  become: true

  vars:
    # Directorio de salida en la misma ruta del playbook
    output_dir: "{{ playbook_dir }}/Salidas_Playbooks"

    # Evidencia técnica consolidada (base para el Excel)
    output_json: "{{ output_dir }}/curl_audit.json"

    # Reporte final para responder a Ciber
    output_xlsx: "{{ output_dir }}/curl_audit_report.xlsx"

    # Script Python ubicado en la misma ruta del playbook
    python_script: "{{ playbook_dir }}/curl_audit_to_excel.py"

  tasks:

    #####################################################################
    # TASK: Obtener facts de paquetes instalados
    # OBJETIVO:
    # - Tener evidencia de versiones de paquetes curl/libcurl vía gestor (rpm/zypper)
    # - Útil si el binario "curl" no está en PATH, pero el paquete existe
    #####################################################################
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto


    #####################################################################
    # TASK: Verificar si el binario curl existe en el PATH
    # OBJETIVO: Confirmar si el comando curl está disponible para ejecutar
    #####################################################################
    - name: Check if curl binary exists
      ansible.builtin.command: "command -v curl"
      register: curl_path
      changed_when: false
      failed_when: false


    #####################################################################
    # TASK: Obtener salida de "curl --version"
    # OBJETIVO:
    # - Extraer versión de curl/libcurl y backend SSL (OpenSSL/GnuTLS/NSS/etc.)
    # NOTA: Solo se ejecuta si existe el binario curl
    #####################################################################
    - name: Get curl short version line
      ansible.builtin.command: "curl --version"
      register: curl_version_cmd
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Obtener salida de "curl -V"
    # OBJETIVO:
    # - Detectar indicios de soporte de protocolos (ldap, sftp, scp, etc.)
    # - Detectar menciones de libssh/libssh2
    # NOTA: Solo se ejecuta si existe el binario curl
    #####################################################################
    - name: Get curl verbose features
      ansible.builtin.command: "curl -V"
      register: curl_v_cmd
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Extraer versión de paquetes instalados (fallback)
    # OBJETIVO:
    # - Si curl no está en PATH, igual intentar sacar versión desde packages facts
    #####################################################################
    - name: Set package versions (fallback if curl command not available)
      ansible.builtin.set_fact:
        curl_pkg_version: >-
          {{
            (ansible_facts.packages['curl'][0].version ~ '-' ~ ansible_facts.packages['curl'][0].release)
            if ('curl' in ansible_facts.packages and ansible_facts.packages['curl']|length > 0)
            else ""
          }}
        libcurl_pkg_version: >-
          {{
            (ansible_facts.packages['libcurl'][0].version ~ '-' ~ ansible_facts.packages['libcurl'][0].release)
            if ('libcurl' in ansible_facts.packages and ansible_facts.packages['libcurl']|length > 0)
            else ""
          }}


    #####################################################################
    # TASK: Normalizar datos de curl/libcurl y “indicios” requeridos
    # OBJETIVO:
    # - Definir curl_installed (bool)
    # - Definir curl_version y libcurl_version (preferir comando; fallback paquete)
    # - Definir backend SSL hint
    # - Definir indicios: GnuTLS, libssh/libssh2, soporte LDAP/SFTP
    #####################################################################
    - name: Parse curl information and hints
      ansible.builtin.set_fact:
        # “Instalado” si hay binario o paquete instalado
        curl_installed: "{{ (curl_path.rc == 0) or (curl_pkg_version | length > 0) }}"

        # Versión curl: preferir comando, si no usar versión del paquete
        curl_version: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[1])
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0)
            else (curl_pkg_version | default(''))
          }}

        # Versión libcurl: preferir comando, si no usar versión del paquete
        libcurl_version: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[2].replace('libcurl/',''))
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0 and 'libcurl/' in curl_version_cmd.stdout_lines[0])
            else (libcurl_pkg_version | default(''))
          }}

        # Backend SSL: normalmente es el 4to token de la primera línea
        ssl_backend_hint: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[3])
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0 and (curl_version_cmd.stdout_lines[0].split()|length > 3))
            else ""
          }}

        # Indicio de GnuTLS (si aparece en texto)
        uses_gnutls: "{{ (curl_version_cmd.stdout | default('')) is search('GnuTLS') }}"

        # Indicio de libssh/libssh2 (si aparece en curl -V)
        uses_libssh_or_libssh2: "{{ (curl_v_cmd.stdout | default('')) is search('libssh') or (curl_v_cmd.stdout | default('')) is search('libssh2') }}"

        # Indicios de soporte de protocolos (NO confirma uso real, solo soporte del binario)
        supports_ldap: "{{ (curl_v_cmd.stdout | default('') | lower) is search('\\bldap\\b') or (curl_v_cmd.stdout | default('') | lower) is search('\\bldaps\\b') }}"
        supports_sftp: "{{ (curl_v_cmd.stdout | default('') | lower) is search('\\bsftp\\b') }}"
      when: true


    #####################################################################
    # TASK: Construir registro por host (lo mínimo necesario para el Excel)
    # OBJETIVO:
    # - Guardar IP (ansible_host), hostname, OS y datos curl
    # - Guardar indicios (gnutls/libssh/ldap/sftp)
    #####################################################################
    - name: Build per-host audit record
      ansible.builtin.set_fact:
        curl_audit_record:
          ip_from_inventory: "{{ hostvars[inventory_hostname].ansible_host | default('') }}"
          hostname: "{{ ansible_hostname | default('') }}"
          os: "{{ ansible_distribution | default('') }}"
          curl_installed: "{{ curl_installed }}"
          curl_version: "{{ curl_version }}"
          libcurl_version: "{{ libcurl_version }}"
          ssl_backend_hint: "{{ ssl_backend_hint }}"
          uses_gnutls: "{{ uses_gnutls }}"
          uses_libssh_or_libssh2: "{{ uses_libssh_or_libssh2 }}"
          supports_ldap: "{{ supports_ldap }}"
          supports_sftp: "{{ supports_sftp }}"
          affected_range: "7.17.0 - 8.17.0"


    #####################################################################
    # TASK: Consolidar todos los registros en el controlador
    # OBJETIVO: Un solo JSON consolidado para todo el inventario
    #####################################################################
    - name: Aggregate all host records on controller
      ansible.builtin.set_fact:
        curl_audit_all: "{{ (curl_audit_all | default([])) + [ hostvars[item].curl_audit_record ] }}"
      loop: "{{ ansible_play_hosts_all }}"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # TASK: Guardar JSON consolidado
    # OBJETIVO: Evidencia técnica base para auditoría y para el Excel
    #####################################################################
    - name: Write consolidated JSON on controller
      ansible.builtin.copy:
        dest: "{{ output_json }}"
        content: "{{ curl_audit_all | to_nice_json }}"
        mode: "0644"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # TASK: Ejecutar Python desde el playbook para generar el Excel final
    # OBJETIVO:
    # - Generar XLSX con columnas mínimas
    # - Colorear SOLO la celda "VERSION AFECTADA" (SI=rojo, NO=verde)
    #####################################################################
    - name: Generate Excel report from JSON on controller
      ansible.builtin.command: >
        python3 "{{ python_script }}" "{{ output_json }}" "{{ output_xlsx }}"
      register: excel_gen
      changed_when: true
      failed_when: excel_gen.rc != 0
      run_once: true
      delegate_to: localhost
