---
- name: Auditoria curl/libcurl + Generacion Excel (AFECTADA SI/NO + whatrequires)
  hosts: SERVERS_LINUX
  gather_facts: true
  become: true

  vars:
    # Carpeta de salida (en el controlador / máquina donde ejecutas ansible)
    output_dir: "{{ playbook_dir }}/Salidas_Playbooks"

    # Salidas
    output_json: "{{ output_dir }}/curl_audit.json"
    output_xlsx: "{{ output_dir }}/curl_audit_report.xlsx"

    # Script Python (debe estar al lado del playbook)
    python_script: "{{ playbook_dir }}/curl_audit_to_excel.py"

    # Rango fijo solicitado por Ciber
    affected_range_str: "7.17.0 - 8.17.0 (inclusive)"
    affected_min_str: "7.17.0"
    affected_max_str: "8.17.0"

  tasks:

    #####################################################################
    # 1) Crear carpeta de salida en el controlador
    #####################################################################
    - name: Ensure output directory exists on controller
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: "0755"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # 2) Construir OS completo (incluye versión y SP para SLES)
    #####################################################################
    - name: Build OS full name
      ansible.builtin.set_fact:
        os_full: >-
          {% set d = ansible_distribution | default('') %}
          {% set v = ansible_distribution_version | default('') %}
          {% if (d | lower) is search('suse') or (d | lower) is search('sles') %}
          {% set major = (v.split('.')[0] | default('')) %}
          {% set minor = (v.split('.')[1] | default('')) %}
          SLES {{ major }} SP{{ minor }}
          {% else %}
          {{ d }} {{ v }}
          {% endif %}


    #####################################################################
    # 3) Inicializar variables (evita undefined aunque un "when" no corra)
    #####################################################################
    - name: Initialize evidence variables to avoid undefined
      ansible.builtin.set_fact:
        evidence_curl_version_line: ""
        evidence_protocols_line: ""
        evidence_features_line: ""
        parsed_backend_ssl_str: ""
        parsed_curl_version_str: ""
        parsed_libcurl_version_str: ""

        curl_pkg_version: ""
        libcurl_pkg_version: ""
        curl_pkg_release: ""
        libcurl_pkg_release: ""

        curl_installed: false
        curl_version: ""
        libcurl_version: ""
        curl_version_norm: "0.0.0"

        backend_ssl: ""
        uses_gnutls: false
        uses_libssh: false

        supports_ldap: false
        supports_ldaps: false
        supports_sftp: false
        supports_scp: false
        supports_http3: false

        affected_bundle: false

        libcurl_whatrequires: ""


    #####################################################################
    # 4) Verificar si existe el binario curl en PATH (para evidencias)
    #####################################################################
    - name: Check if curl binary exists
      ansible.builtin.shell: "command -v curl 2>/dev/null || true"
      register: curl_path
      changed_when: false
      failed_when: false


    #####################################################################
    # 5) Obtener versión de curl/libcurl por rpm -q (universal en distros RPM)
    #####################################################################
    - name: Get curl package VERSION/RELEASE by rpm -q
      ansible.builtin.shell: "rpm -q curl --qf '%{VERSION} %{RELEASE}\\n' 2>/dev/null || true"
      register: rpm_q_curl
      changed_when: false
      failed_when: false

    - name: Get libcurl package VERSION/RELEASE by rpm -q (try common names)
      ansible.builtin.shell: |
        set -o pipefail
        (rpm -q libcurl --qf '%{VERSION} %{RELEASE}\n' 2>/dev/null) || \
        (rpm -q libcurl4 --qf '%{VERSION} %{RELEASE}\n' 2>/dev/null) || \
        (rpm -q libcurl4-gnutls --qf '%{VERSION} %{RELEASE}\n' 2>/dev/null) || \
        true
      register: rpm_q_libcurl
      changed_when: false
      failed_when: false


    #####################################################################
    # 6) Parsear VERSION/RELEASE desde rpm -q
    #####################################################################
    - name: Parse rpm -q outputs into variables
      ansible.builtin.set_fact:
        curl_pkg_version: "{{ (rpm_q_curl.stdout | default('') | trim).split(' ')[0] | default('') }}"
        curl_pkg_release: "{{ (rpm_q_curl.stdout | default('') | trim).split(' ')[1] | default('') }}"
        libcurl_pkg_version: "{{ (rpm_q_libcurl.stdout | default('') | trim).split(' ')[0] | default('') }}"
        libcurl_pkg_release: "{{ (rpm_q_libcurl.stdout | default('') | trim).split(' ')[1] | default('') }}"


    #####################################################################
    # 7) Evidencia - curl --version / -V (solo si hay binario)
    #####################################################################
    - name: Evidence - curl --version first line
      ansible.builtin.shell: "curl --version 2>/dev/null | head -1"
      register: ev_curl_version
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0

    - name: Evidence - curl -V Protocols line
      ansible.builtin.shell: "curl -V 2>/dev/null | awk '/^Protocols:/{print $0}'"
      register: ev_protocols
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0

    - name: Evidence - curl -V Features line
      ansible.builtin.shell: "curl -V 2>/dev/null | awk '/^Features:/{print $0}'"
      register: ev_features
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0


    #####################################################################
    # 8) Parsear curl/libcurl/backend desde curl --version (si hay binario)
    #####################################################################
    - name: Parse curl version (awk)
      ansible.builtin.shell: "curl --version 2>/dev/null | head -1 | awk '{print $2}'"
      register: parsed_curl_version
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0

    - name: Parse libcurl version (awk)
      ansible.builtin.shell: |
        curl --version 2>/dev/null | head -1 | awk '{
          for(i=1;i<=NF;i++){
            if($i ~ /^libcurl\//){
              gsub(/^libcurl\//,"",$i);
              print $i; exit
            }
          }
        }'
      register: parsed_libcurl_version
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0

    - name: Parse backend SSL (awk)
      ansible.builtin.shell: |
        curl --version 2>/dev/null | head -1 | awk '{
          for(i=1;i<=NF;i++){
            if($i ~ /^(OpenSSL|GnuTLS|NSS|wolfSSL|mbedTLS|Schannel|LibreSSL|BoringSSL|rustls)\//){
              print $i; exit
            }
          }
        }'
      register: parsed_backend_ssl
      changed_when: false
      failed_when: false
      when: (curl_path.stdout | default('') | trim) | length > 0


    #####################################################################
    # 9) Normalizar outputs registrados a strings seguros (si hay binario)
    #####################################################################
    - name: Normalize registered outputs into safe strings
      ansible.builtin.set_fact:
        evidence_curl_version_line: "{{ (ev_curl_version.stdout | default('') | trim) }}"
        evidence_protocols_line: "{{ (ev_protocols.stdout | default('') | trim) }}"
        evidence_features_line: "{{ (ev_features.stdout | default('') | trim) }}"
        parsed_curl_version_str: "{{ (parsed_curl_version.stdout | default('') | trim) }}"
        parsed_libcurl_version_str: "{{ (parsed_libcurl_version.stdout | default('') | trim) }}"
        parsed_backend_ssl_str: "{{ (parsed_backend_ssl.stdout | default('') | trim) }}"
      when: (curl_path.stdout | default('') | trim) | length > 0


    #####################################################################
    # 10) Consolidar valores finales (prefiere comando, si no rpm)
    #####################################################################
    - name: Consolidate final values
      ansible.builtin.set_fact:
        curl_installed: >-
          {{
            ((curl_path.stdout | default('') | trim) | length > 0)
            or (curl_pkg_version | length > 0)
          }}

        curl_version: >-
          {{
            parsed_curl_version_str
            if (parsed_curl_version_str | length > 0)
            else (curl_pkg_version | default(''))
          }}

        libcurl_version: >-
          {{
            parsed_libcurl_version_str
            if (parsed_libcurl_version_str | length > 0)
            else (libcurl_pkg_version | default(''))
          }}

        backend_ssl: "{{ parsed_backend_ssl_str }}"

        uses_gnutls: "{{ parsed_backend_ssl_str is search('^GnuTLS/') }}"

        uses_libssh: >-
          {{
            (evidence_features_line ~ ' ' ~ evidence_protocols_line) is search('libssh')
            or (evidence_features_line ~ ' ' ~ evidence_protocols_line) is search('libssh2')
          }}

        supports_ldap: "{{ (evidence_protocols_line | lower) is search('\\bldap\\b') }}"
        supports_ldaps: "{{ (evidence_protocols_line | lower) is search('\\bldaps\\b') }}"
        supports_sftp: "{{ (evidence_protocols_line | lower) is search('\\bsftp\\b') }}"
        supports_scp: "{{ (evidence_protocols_line | lower) is search('\\bscp\\b') }}"
        supports_http3: "{{ (evidence_features_line | upper) is search('\\bHTTP3\\b') }}"


    #####################################################################
    # 11) Normalizar versión a X.Y.Z (task separado)
    #####################################################################
    - name: Normalize curl version to X.Y.Z
      ansible.builtin.set_fact:
        curl_version_norm: "{{ (curl_version | default('') | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)')) | default('0.0.0', true) }}"


    #####################################################################
    # 12) Construir listas de enteros (task separado)
    #####################################################################
    - name: Build version arrays for comparison
      ansible.builtin.set_fact:
        curl_v: "{{ curl_version_norm.split('.') | map('int') | list }}"
        min_v: "{{ affected_min_str.split('.') | map('int') | list }}"
        max_v: "{{ affected_max_str.split('.') | map('int') | list }}"


    #####################################################################
    # 13) Evaluar afectación (task separado)
    #####################################################################
    - name: Compute affected range (safe list compare)
      ansible.builtin.set_fact:
        affected_bundle: "{{ (curl_installed | bool) and (curl_version_norm != '0.0.0') and (curl_v >= min_v) and (curl_v <= max_v) }}"


    #####################################################################
    # 14) Identificar paquetes que dependen de libcurl (rpm whatrequires)
    #####################################################################
    - name: Get packages that require libcurl (rpm whatrequires)
      ansible.builtin.shell: |
        set -o pipefail
        if rpm -q libcurl >/dev/null 2>&1; then
          PKG="libcurl"
        elif rpm -q libcurl4 >/dev/null 2>&1; then
          PKG="libcurl4"
        elif rpm -q libcurl4-gnutls >/dev/null 2>&1; then
          PKG="libcurl4-gnutls"
        else
          PKG=""
        fi

        if [ -n "$PKG" ]; then
          rpm -q --whatrequires "$PKG" 2>/dev/null \
            | sed '/^no package requires/d' \
            | sort -u \
            | head -200
        else
          echo ""
        fi
      register: ev_libcurl_whatrequires
      changed_when: false
      failed_when: false
      when: curl_installed

    - name: Normalize whatrequires output
      ansible.builtin.set_fact:
        libcurl_whatrequires: "{{ (ev_libcurl_whatrequires.stdout | default('') | trim) }}"
      when: curl_installed


    #####################################################################
    # 15) Registro por host (mínimo + evidencias)
    #####################################################################
    - name: Build per-host audit record
      ansible.builtin.set_fact:
        curl_audit_record:
          ip_from_inventory: "{{ hostvars[inventory_hostname].ansible_host | default('') }}"
          hostname: "{{ ansible_hostname | default('') }}"
          os: "{{ os_full }}"

          curl_installed: "{{ curl_installed }}"

          curl_version: "{{ curl_version }}"
          curl_version_norm: "{{ curl_version_norm }}"
          libcurl_version: "{{ libcurl_version }}"

          affected_range: "{{ affected_range_str }}"
          affected_bundle: "{{ affected_bundle }}"

          backend_ssl: "{{ backend_ssl }}"
          uses_gnutls: "{{ uses_gnutls }}"
          uses_libssh: "{{ uses_libssh }}"

          supports_ldap: "{{ supports_ldap }}"
          supports_ldaps: "{{ supports_ldaps }}"
          supports_sftp: "{{ supports_sftp }}"
          supports_scp: "{{ supports_scp }}"
          supports_http3: "{{ supports_http3 }}"

          libcurl_whatrequires: "{{ libcurl_whatrequires }}"

          evidence_curl_version_line: "{{ evidence_curl_version_line }}"
          evidence_protocols_line: "{{ evidence_protocols_line }}"
          evidence_features_line: "{{ evidence_features_line }}"


    #####################################################################
    # 16) Consolidar todos los registros en el controlador (run_once)
    #####################################################################
    - name: Aggregate all host records on controller
      ansible.builtin.set_fact:
        curl_audit_all: "{{ (curl_audit_all | default([])) + [ hostvars[item].curl_audit_record ] }}"
      loop: "{{ ansible_play_hosts_all }}"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # 17) Guardar JSON consolidado en el controlador
    #####################################################################
    - name: Write consolidated JSON on controller
      ansible.builtin.copy:
        dest: "{{ output_json }}"
        content: "{{ curl_audit_all | to_nice_json }}"
        mode: "0644"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # 18) Generar Excel desde el JSON (controller)
    #####################################################################
    - name: Generate Excel report from JSON on controller
      ansible.builtin.command: >
        python3 "{{ python_script }}" "{{ output_json }}" "{{ output_xlsx }}"
      register: excel_gen
      changed_when: true
      failed_when: excel_gen.rc != 0
      run_once: true
      delegate_to: localhost