---
- name: Auditoria curl/libcurl y generacion de Excel para respuesta a Ciber
  hosts: all
  gather_facts: true
  become: true

  vars:
    # Carpeta de salida en la misma ruta del playbook (yml principal)
    output_dir: "{{ playbook_dir }}/Salidas_Playbooks"
    output_json: "{{ output_dir }}/curl_audit.json"
    output_xlsx: "{{ output_dir }}/curl_audit_report.xlsx"

    # Script Python que genera el Excel (misma ruta del playbook)
    python_script: "{{ playbook_dir }}/curl_audit_to_excel.py"

  tasks:


    #######################################################################
    # TASK: Capturar info de paquetes instalados (rpm/zypper)
    # OBJETIVO:
    # - Detectar versiones de paquetes curl y libcurl aun si "curl" no está en PATH
    # - Funciona para RHEL/CentOS/Oracle (RPM) y SLES (zypper/rpm)
    #######################################################################
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto


    #######################################################################
    # TASK: Verificar si existe el binario curl en el PATH
    # OBJETIVO: Confirmar instalación funcional del comando curl
    #######################################################################
    - name: Check if curl binary exists
      ansible.builtin.command: "command -v curl"
      register: curl_path
      changed_when: false
      failed_when: false


    #######################################################################
    # TASK: Obtener salida de 'curl --version'
    # OBJETIVO:
    # - Extraer curl version / libcurl version / backend SSL (OpenSSL/GnuTLS/NSS/etc)
    #######################################################################
    - name: Get curl short version line
      ansible.builtin.command: "curl --version"
      register: curl_version_cmd
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #######################################################################
    # TASK: Obtener salida de 'curl -V'
    # OBJETIVO:
    # - Extraer protocolos soportados (ldap/ldaps/sftp/scp/http/https, etc.)
    # - Detectar indicios de librerias SSH (libssh/libssh2)
    #######################################################################
    - name: Get curl verbose features
      ansible.builtin.command: "curl -V"
      register: curl_v_cmd
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #######################################################################
    # TASK: Normalizar versión de paquetes (curl/libcurl) desde package_facts
    # OBJETIVO:
    # - Obtener la versión de paquete si existe, para usarla como fallback
    # NOTA: package_facts devuelve lista de paquetes por nombre
    #######################################################################
    - name: Set package versions (fallback if curl command not available)
      ansible.builtin.set_fact:
        curl_pkg_version: >-
          {{
            (ansible_facts.packages['curl'][0].version ~ '-' ~ ansible_facts.packages['curl'][0].release)
            if ('curl' in ansible_facts.packages and ansible_facts.packages['curl']|length > 0)
            else ""
          }}
        libcurl_pkg_version: >-
          {{
            (ansible_facts.packages['libcurl'][0].version ~ '-' ~ ansible_facts.packages['libcurl'][0].release)
            if ('libcurl' in ansible_facts.packages and ansible_facts.packages['libcurl']|length > 0)
            else ""
          }}


    #######################################################################
    # TASK: Parsear información de curl (si el comando existe)
    # OBJETIVO:
    # - curl_installed (bool)
    # - curl_version (preferible desde curl --version, si no, desde paquete)
    # - libcurl_version (igual)
    # - backend SSL hint (OpenSSL/GnuTLS/NSS/etc.)
    # - protocolos soportados (ldap/ldaps/sftp/scp/http/https...) como indicio
    #######################################################################
    - name: Parse curl information and backend/protocol hints
      ansible.builtin.set_fact:
        curl_installed: "{{ (curl_path.rc == 0) or (curl_pkg_version|length > 0) }}"

        # Versión principal de curl: usar comando si existe, si no usar versión de paquete
        curl_version_detected: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[1])
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0)
            else (curl_pkg_version | default(''))
          }}

        # Versión de libcurl: usar comando si existe, si no usar paquete libcurl
        libcurl_version_detected: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[2].replace('libcurl/',''))
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0 and 'libcurl/' in curl_version_cmd.stdout_lines[0])
            else (libcurl_pkg_version | default(''))
          }}

        # Backend SSL: normalmente aparece como 4to token en primera línea
        ssl_backend_hint: >-
          {{
            (curl_version_cmd.stdout_lines[0].split()[3])
            if (curl_path.rc == 0 and curl_version_cmd.stdout_lines|length > 0 and (curl_version_cmd.stdout_lines[0].split()|length > 3))
            else ""
          }}

        # Indicio explícito de GnuTLS en la cadena (si aparece)
        uses_gnutls: "{{ (curl_version_cmd.stdout | default('')) is search('GnuTLS') }}"

        # Indicio de libssh/libssh2 (si curl -V menciona estas librerías)
        uses_libssh_or_libssh2: "{{ (curl_v_cmd.stdout | default('')) is search('libssh') or (curl_v_cmd.stdout | default('')) is search('libssh2') }}"

        # Protocolos soportados (indicio): si curl -V existe, buscamos palabras clave
        supports_ldap: "{{ (curl_v_cmd.stdout | default('') | lower) is search('\\bldap\\b') or (curl_v_cmd.stdout | default('') | lower) is search('\\bldaps\\b') }}"
        supports_sftp: "{{ (curl_v_cmd.stdout | default('') | lower) is search('\\bsftp\\b') }}"
        supports_scp: "{{ (curl_v_cmd.stdout | default('') | lower) is search('\\bscp\\b') }}"
      when: true


    #######################################################################
    # TASK: Construir campos “respuesta a Ciber” (lo que te preguntaron)
    # OBJETIVO:
    # - Q1: curl/libcurl instalado
    # - Q2: libcurl embebido -> NO se puede afirmar sin análisis de apps (marcar "REQUIERE VALIDACION APP")
    # - Q3: backend libssh o GnuTLS -> se responde con indicios
    # - Q4: tokens OAuth -> NO se confirma a nivel OS (marcar "REQUIERE VALIDACION APP")
    # - Q5: LDAP/SFTP automatizados -> indicio por soporte de protocolos (no confirma uso real)
    #######################################################################
    - name: Build Ciber Q&A fields
      ansible.builtin.set_fact:
        ciber_q1_curl_installed: "{{ curl_installed }}"
        ciber_q2_embedded_libcurl: "REQUIERE VALIDACION APP"
        ciber_q3_backend_libssh_or_gnutls: "{{ (uses_libssh_or_libssh2 or uses_gnutls) }}"
        ciber_q4_oauth_tokens_via_curl: "REQUIERE VALIDACION APP"
        ciber_q5_ldap_or_sftp_integrations: "{{ (supports_ldap or supports_sftp or supports_scp) }}"


    #######################################################################
    # TASK: Crear registro por host para el JSON/Excel
    # OBJETIVO: Consolidar IP/hostname/OS/versions + respuestas a Ciber
    #######################################################################
    - name: Build per-host audit record
      ansible.builtin.set_fact:
        curl_audit_record:
          ip_from_inventory: "{{ hostvars[inventory_hostname].ansible_host | default('') }}"
          inventory_name: "{{ inventory_hostname }}"
          hostname: "{{ ansible_hostname | default('') }}"
          fqdn: "{{ ansible_fqdn | default('') }}"
          os: "{{ ansible_distribution | default('') }}"
          os_version: "{{ ansible_distribution_version | default('') }}"
          kernel: "{{ ansible_kernel | default('') }}"

          curl_installed: "{{ ciber_q1_curl_installed }}"
          curl_version: "{{ curl_version_detected }}"
          libcurl_version: "{{ libcurl_version_detected }}"

          ssl_backend_hint: "{{ ssl_backend_hint }}"
          uses_gnutls: "{{ uses_gnutls }}"
          uses_libssh_or_libssh2: "{{ uses_libssh_or_libssh2 }}"

          supports_ldap: "{{ supports_ldap }}"
          supports_sftp: "{{ supports_sftp }}"
          supports_scp: "{{ supports_scp }}"

          affected_range: "7.17.0 - 8.17.0"

          # Respuestas alineadas a las 5 preguntas de Ciber
          ciber_q1: "{{ ciber_q1_curl_installed }}"
          ciber_q2: "{{ ciber_q2_embedded_libcurl }}"
          ciber_q3: "{{ ciber_q3_backend_libssh_or_gnutls }}"
          ciber_q4: "{{ ciber_q4_oauth_tokens_via_curl }}"
          ciber_q5: "{{ ciber_q5_ldap_or_sftp_integrations }}"


    #######################################################################
    # TASK: Consolidar registros de todos los hosts en el controlador
    # OBJETIVO: Un solo JSON para todo el inventario
    #######################################################################
    - name: Aggregate all host records on controller
      ansible.builtin.set_fact:
        curl_audit_all: "{{ (curl_audit_all | default([])) + [ hostvars[item].curl_audit_record ] }}"
      loop: "{{ ansible_play_hosts_all }}"
      run_once: true
      delegate_to: localhost


    #######################################################################
    # TASK: Guardar JSON consolidado en Salidas_Playbooks (controlador)
    # OBJETIVO: Evidencia base para auditoría y para generar Excel
    #######################################################################
    - name: Write consolidated JSON on controller
      ansible.builtin.copy:
        dest: "{{ output_json }}"
        content: "{{ curl_audit_all | to_nice_json }}"
        mode: "0644"
      run_once: true
      delegate_to: localhost



    #######################################################################
    # TASK: Ejecutar el Python desde el playbook para generar el Excel
    # OBJETIVO:
    # - Crear XLSX con columna 'VERSION AFECTADA (SI/NO)'
    # - SI en rojo, NO en verde
    # - Columnas de respuesta a preguntas de Ciber
    #######################################################################
    - name: Generate Excel report from JSON on controller
      ansible.builtin.command: >
        python3 "{{ python_script }}" "{{ output_json }}" "{{ output_xlsx }}"
      register: excel_gen
      changed_when: true
      failed_when: excel_gen.rc != 0
      run_once: true
      delegate_to: localhost
