---
- name: Auditoria curl/libcurl + Generacion Excel (VERSION AFECTADA SI/NO)
  hosts: prueba
  gather_facts: true
  become: true

  vars:
    output_dir: "{{ playbook_dir }}/Salidas_Playbooks"
    output_json: "{{ output_dir }}/curl_audit.json"
    output_xlsx: "{{ output_dir }}/curl_audit_report.xlsx"
    python_script: "{{ playbook_dir }}/curl_audit_to_excel.py"

  tasks:

    #####################################################################
    # TASK: Crear carpeta de salida en el controlador
    #####################################################################
    - name: Ensure output directory exists on controller
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: "0755"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # TASK: Obtener facts de paquetes instalados (rpm/zypper)
    #####################################################################
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto


    #####################################################################
    # TASK: Construir OS completo (incluye versión y SP para SLES)
    #####################################################################
    - name: Build OS full name
      ansible.builtin.set_fact:
        os_full: >-
          {% set d = ansible_distribution | default('') %}
          {% set v = ansible_distribution_version | default('') %}
          {% if (d | lower) is search('suse') or (d | lower) is search('sles') %}
          {% set major = (v.split('.')[0] | default('')) %}
          {% set minor = (v.split('.')[1] | default('')) %}
          SLES {{ major }} SP{{ minor }}
          {% else %}
          {{ d }} {{ v }}
          {% endif %}


    #####################################################################
    # TASK: Inicializar variables (evita undefined en cualquier host)
    #####################################################################
    - name: Initialize evidence variables to avoid undefined
      ansible.builtin.set_fact:
        evidence_curl_version_line: ""
        evidence_protocols_line: ""
        evidence_features_line: ""
        parsed_backend_ssl_str: ""
        parsed_curl_version_str: ""
        parsed_libcurl_version_str: ""


    #####################################################################
    # TASK: Verificar si existe el binario curl en PATH
    #####################################################################
    - name: Check if curl binary exists
      ansible.builtin.command: "command -v curl"
      register: curl_path
      changed_when: false
      failed_when: false


    #####################################################################
    # TASK: Fallback de versión desde package_facts
    #####################################################################
    - name: Set package versions fallback
      ansible.builtin.set_fact:
        curl_pkg_version: >-
          {{
            (ansible_facts.packages['curl'][0].version)
            if ('curl' in ansible_facts.packages and ansible_facts.packages['curl']|length > 0)
            else ""
          }}
        libcurl_pkg_version: >-
          {{
            (ansible_facts.packages['libcurl'][0].version)
            if ('libcurl' in ansible_facts.packages and ansible_facts.packages['libcurl']|length > 0)
            else ""
          }}


    #####################################################################
    # TASK: Evidencia - curl --version primera línea
    #####################################################################
    - name: Evidence - curl --version first line
      ansible.builtin.shell: "curl --version 2>/dev/null | head -1"
      register: ev_curl_version
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Evidencia - Protocols: y Features: desde curl -V
    #####################################################################
    - name: Evidence - curl -V Protocols line
      ansible.builtin.shell: "curl -V 2>/dev/null | awk '/^Protocols:/{print $0}'"
      register: ev_protocols
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0

    - name: Evidence - curl -V Features line
      ansible.builtin.shell: "curl -V 2>/dev/null | awk '/^Features:/{print $0}'"
      register: ev_features
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Parsear curl/libcurl/backend con awk (solo si curl existe)
    #####################################################################
    - name: Parse curl version (awk)
      ansible.builtin.shell: "curl --version 2>/dev/null | head -1 | awk '{print $2}'"
      register: parsed_curl_version
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0

    - name: Parse libcurl version (awk)
      ansible.builtin.shell: |
        curl --version 2>/dev/null | head -1 | awk '{
          for(i=1;i<=NF;i++){
            if($i ~ /^libcurl\//){
              gsub(/^libcurl\//,"",$i);
              print $i; exit
            }
          }
        }'
      register: parsed_libcurl_version
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0

    - name: Parse backend SSL (awk)
      ansible.builtin.shell: |
        curl --version 2>/dev/null | head -1 | awk '{
          for(i=1;i<=NF;i++){
            if($i ~ /^(OpenSSL|GnuTLS|NSS|wolfSSL|mbedTLS|Schannel)\//){
              print $i; exit
            }
          }
        }'
      register: parsed_backend_ssl
      changed_when: false
      failed_when: false
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Copiar results de registers a variables normales (si existen)
    # OBJETIVO: que siempre existan strings aunque el when no corra
    #####################################################################
    - name: Normalize registered outputs into safe strings
      ansible.builtin.set_fact:
        evidence_curl_version_line: "{{ (ev_curl_version.stdout | default('') | trim) }}"
        evidence_protocols_line: "{{ (ev_protocols.stdout | default('') | trim) }}"
        evidence_features_line: "{{ (ev_features.stdout | default('') | trim) }}"
        parsed_curl_version_str: "{{ (parsed_curl_version.stdout | default('') | trim) }}"
        parsed_libcurl_version_str: "{{ (parsed_libcurl_version.stdout | default('') | trim) }}"
        parsed_backend_ssl_str: "{{ (parsed_backend_ssl.stdout | default('') | trim) }}"
      when: curl_path.rc == 0


    #####################################################################
    # TASK: Consolidar valores finales (usa comando si hay; si no paquete)
    #####################################################################
    - name: Consolidate final values
      ansible.builtin.set_fact:
        curl_installed: "{{ (curl_path.rc == 0) or (curl_pkg_version | length > 0) }}"

        curl_version: >-
          {{
            parsed_curl_version_str
            if (parsed_curl_version_str | length > 0)
            else (curl_pkg_version | default(''))
          }}

        libcurl_version: >-
          {{
            parsed_libcurl_version_str
            if (parsed_libcurl_version_str | length > 0)
            else (libcurl_pkg_version | default(''))
          }}

        backend_ssl: "{{ parsed_backend_ssl_str }}"

        uses_gnutls: "{{ parsed_backend_ssl_str is search('^GnuTLS/') }}"
        uses_libssh: "{{ (evidence_features_line ~ ' ' ~ evidence_protocols_line) is search('libssh') or (evidence_features_line ~ ' ' ~ evidence_protocols_line) is search('libssh2') }}"
        supports_ldap: "{{ (evidence_protocols_line | lower) is search('\\bldap\\b') or (evidence_protocols_line | lower) is search('\\bldaps\\b') }}"
        supports_sftp: "{{ (evidence_protocols_line | lower) is search('\\bsftp\\b') }}"


    #####################################################################
    # TASK: Registro por host (mínimo + evidencias)
    #####################################################################
    - name: Build per-host audit record
      ansible.builtin.set_fact:
        curl_audit_record:
          ip_from_inventory: "{{ hostvars[inventory_hostname].ansible_host | default('') }}"
          hostname: "{{ ansible_hostname | default('') }}"
          os: "{{ os_full }}"

          curl_installed: "{{ curl_installed }}"
          curl_version: "{{ curl_version }}"
          libcurl_version: "{{ libcurl_version }}"
          backend_ssl: "{{ backend_ssl }}"

          uses_gnutls: "{{ uses_gnutls }}"
          uses_libssh: "{{ uses_libssh }}"
          supports_ldap: "{{ supports_ldap }}"
          supports_sftp: "{{ supports_sftp }}"

          affected_range: "7.17.0 - 8.17.0"

          evidence_curl_version_line: "{{ evidence_curl_version_line }}"
          evidence_protocols_line: "{{ evidence_protocols_line }}"
          evidence_features_line: "{{ evidence_features_line }}"


    #####################################################################
    # TASK: Consolidar todos los registros en el controlador
    #####################################################################
    - name: Aggregate all host records on controller
      ansible.builtin.set_fact:
        curl_audit_all: "{{ (curl_audit_all | default([])) + [ hostvars[item].curl_audit_record ] }}"
      loop: "{{ ansible_play_hosts_all }}"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # TASK: Guardar JSON consolidado
    #####################################################################
    - name: Write consolidated JSON on controller
      ansible.builtin.copy:
        dest: "{{ output_json }}"
        content: "{{ curl_audit_all | to_nice_json }}"
        mode: "0644"
      run_once: true
      delegate_to: localhost


    #####################################################################
    # TASK: Generar Excel desde el JSON (controller)
    #####################################################################
    - name: Generate Excel report from JSON on controller
      ansible.builtin.command: >
        python3 "{{ python_script }}" "{{ output_json }}" "{{ output_xlsx }}"
      register: excel_gen
      changed_when: true
      failed_when: excel_gen.rc != 0
      run_once: true
      delegate_to: localhost
