ansible_connection: winrm
ansible_user: "COLOMBIANA\\1026278709"
ansible_password: "{{ vault_winrm_password }}"
ansible_port: 5985
#ansible_winrm_transport: basic
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

