
[REPORTES]
vm-prd-appps-bog-08 ansible_host=172.25.96.96

[oracle]
CKPR1 ansible_host=172.25.87.110
CKPR2 ansible_host=172.25.87.120
WMS1 ansible_host=192.168.97.53
WMS2 ansible_host=192.168.97.54
CKPRU1 ansible_host=172.25.77.107
ALKANA1 ansible_host=192.168.97.45
ALKANA2 ansible_host=192.168.97.46
GSPSPEC ansible_host=10.181.3.156
OIM ansible_host=10.181.3.79

[AWS]
VM-EU1-BASTION-GEO-PRD ansible_host=52.202.112.149

[mysql]
CORBEMOVIL ansible_host=10.181.0.21
MOVILTRACK ansible_host=10.181.3.109
MERCADERISTAS ansible_host=10.181.3.23
DESPACHOS-DIGI ansible_host=10.181.4.244

[linux:children]
oracle
mysql

[all:vars]
#ansible_user=usuario_ansible
ansible_become=true


##### INVENTARIO 2026 - On-Premise ####

[PPU]
ANSIBLEAWXBOGDIS01           ansible_host=10.181.5.247
ANSIBLEDBBOGDIS01            ansible_host=10.181.5.248
ANSIBLEFOREBOGDIS01          ansible_host=10.181.5.239
ANSIBLEGRAFANABOGDIS01       ansible_host=10.181.5.249
APBOGDISCRMCOLC              ansible_host=10.181.5.29
APBOGDISILMT01               ansible_host=10.181.11.153
APBOGDISILMT01-Ansible       ansible_host=10.181.8.231
APLINETIDIBOG01              ansible_host=10.181.3.217
APORACLEIDMAN01              ansible_host=10.181.3.77
APORACLEIDMAN02              ansible_host=10.181.3.203
APPBOGDISMOVILTRACKQA2       ansible_host=10.181.11.103
APPDESPADOCK_PRD             ansible_host=10.181.5.64
APPDESPADOCKQA               ansible_host=10.181.11.32  ansible_python_interpreter=/usr/libexec/platform-python
AUDIRHBOGDIS01               ansible_host=10.181.5.252
BATMAN_NEW                   ansible_host=10.181.5.224
CLOUDCONTROL02               ansible_host=10.181.4.245
CONTACTCRMDBBOGDIS01         ansible_host=10.181.5.214
CONTACTCRMDBBOGDIS02         ansible_host=10.181.5.219
CONTACTCRMDBBOGDIS03         ansible_host=10.181.4.103
CORBEMOVIL                   ansible_host=10.181.0.21
CRM_BD1                      ansible_host=10.181.0.152
CRM_BD1_QA                   ansible_host=10.181.11.155
CRM_DESA_CENT7_QA01          ansible_host=10.181.11.192
CRM_FILE                     ansible_host=10.181.3.36
CRM01_K8S                    ansible_host=10.181.3.105
CRM02_K8S                    ansible_host=10.181.11.16
CRM03_K8S                    ansible_host=10.181.3.46
CRM04_K8S                    ansible_host=10.181.4.11
DBDESPACHOS03                ansible_host=10.181.4.244
DBDLX2009                    ansible_host=10.181.5.60
DBFACAUTBOGDIS01             ansible_host=10.181.3.218
DBORACLEIDMAN02              ansible_host=10.181.3.79
DBORACLEIDMANTEST            ansible_host=10.181.11.95
DBREDCONTBOGDIS              ansible_host=10.181.5.70
DESPACHOS03                  ansible_host=10.181.3.106
DNSDISTBOGDIS01              ansible_host=10.181.8.236
EXDA_MANAGATEWAY_PRD         ansible_host=10.181.5.108
GOLDENGATEBOGDIS01           ansible_host=10.181.8.226
gspsmsinergia                ansible_host=10.181.3.156
JASPER_NEW                   ansible_host=10.181.11.241
JASPERSOFT                   ansible_host=10.181.3.61
JASPERSOFTPRU                ansible_host=10.181.11.67
LPBOGDIS01                   ansible_host=10.181.4.16
MANTISBOGDIS01               ansible_host=10.181.5.68
MANTISQABOGDIS01             ansible_host=10.181.11.151
MARCSINERGIA                 ansible_host=10.181.11.78
MERCADERISTASAPP_PRD         ansible_host=10.181.3.144
MERCADERISTASDB_PRD          ansible_host=10.181.3.23
TESTMERCADERISTASDBBOGDIS01  ansible_host=10.181.11.166
MICROCRMBOGDIS2              ansible_host=10.181.5.126
MICROCRMBOGDISTEST           ansible_host=10.181.11.150
MICROSERVICIOS02             ansible_host=10.181.11.145
MICROSERVICIOS04_1           ansible_host=10.181.3.183
MICROSERVICIOS05             ansible_host=10.181.3.28
MICROSERVICIOS06             ansible_host=10.181.3.68
MICROSERVICIOS07             ansible_host=10.181.4.13
MICROSERVICIOS08             ansible_host=10.181.4.14
MICROSERVICIOS09             ansible_host=10.181.4.15
MICROSERVTEST10              ansible_host=10.181.11.112
MON_ZABBIX                   ansible_host=10.181.5.210
MOVILTRACK                   ansible_host=10.181.3.109
MOVILTRACKBOGDIS01           ansible_host=10.181.11.134
NETWORKER04                  ansible_host=10.181.3.104
NOTIBACKUP-PRD               ansible_host=10.181.5.80
NTPBOGDIS-PRD                ansible_host=10.181.0.155
PASBOGDIS01                  ansible_host=10.181.8.208
PIVDRPORABOGDIS01            ansible_host=10.181.3.82
POSHISTORICOS                ansible_host=10.181.0.112
POSHISTORICOS_1              ansible_host=10.181.11.240
POSHISTORICOS_2              ansible_host=10.181.0.111
PRE_TOBIN                    ansible_host=10.181.11.107
PSEBOGDIS01                  ansible_host=10.181.4.106
SICCONTROLAUTO               ansible_host=10.181.4.17
SOCNESUSMNGRITSSBOGDIS01     ansible_host=10.181.8.192
SOCNESUSPROITSSBOGDIS01      ansible_host=10.181.8.191
SOCSCITSSBOGDIS01            ansible_host=10.181.8.193
SRMBOGDIS02                  ansible_host=10.181.6.38
STORAGENODE01                ansible_host=10.181.3.164
STORAGENODE02                ansible_host=10.181.3.163
TEST_IMC_NETWORKING01        ansible_host=10.181.11.77
TEST_MONGO_NODO1             ansible_host=10.181.11.41
TEST_MONGO_NODO1_CLON        ansible_host=10.181.5.204
TEST_MONGO_NODO2             ansible_host=10.181.11.42
TEST_MONGO_NODO2_CLON        ansible_host=10.181.5.205
TEST_MONGO_NODO3             ansible_host=10.181.11.43
TEST_MONGO_NODO3_CLON        ansible_host=10.181.5.206
TESTAPLINETBOGDIS01          ansible_host=10.181.11.79
TESTAPLINETBOGDIS01-Ansible  ansible_host=10.181.8.235
TESTCONTACTCRMDBBOGDIS02     ansible_host=10.181.11.59
TESTDOCKBOGDIS               ansible_host=10.181.11.76
TESTMERCADERISTASAPPBOGDIS01 ansible_host=10.181.11.111
TESTMOVILTRACK               ansible_host=10.181.11.20
TESTORACLEIDMAN              ansible_host=10.181.11.91
Tests4sinergiaval            ansible_host=10.181.11.200
TESTWMSAPPBOGDIS01_N3        ansible_host=10.181.11.83
TESTWMSAPPBOGDIS01_N4        ansible_host=10.181.11.84
WMS_TEST_APP                 ansible_host=10.181.11.117
WMS_TEST_DB02                ansible_host=10.181.11.116
WMS_TEST03_APP               ansible_host=10.181.11.119
WMS_TEST05_APP               ansible_host=10.181.11.101
WMSAPPBOGDIS01_DEV           ansible_host=10.181.11.74
WMSAPPBOGDIS01_N1            ansible_host=10.181.3.65
WMSAPPBOGDIS01_N2            ansible_host=10.181.4.101
WMSAPPBOGDIS01_N3            ansible_host=10.181.4.211
WMSAPPBOGDIS01_N4            ansible_host=10.181.3.84
WMSAPPBOGDIS02               ansible_host=10.181.3.168
WMSAPPBOGDIS02_DEV           ansible_host=10.181.4.181

[INFRA2_0]
DBFACREBOGDIS01    ansible_host=10.181.34.6
GEOPROMONGODB03    ansible_host=10.181.32.3
MONDBMICROBOGDIS01 ansible_host=10.181.34.10
MONDBMICROBOGDIS02 ansible_host=10.181.34.9
MONGO-PRD-N1       ansible_host=10.181.34.3
MONGO-PRD-N2       ansible_host=10.181.34.4
MONGO-PRD-N3       ansible_host=10.181.34.5
OPENSHIFT-BASTION  ansible_host=10.181.40.10
OPENSHIFT-NFS      ansible_host=10.181.40.11

[PPU_GEOPOS]
AKB30-GEODRP             ansible_host=10.181.0.63
AKOMERCAN                ansible_host=10.181.5.28
ALKA1-DRP-CLON           ansible_host=10.181.5.183
ALNI5-S15SP5             ansible_host=10.181.3.178
ALNI6-S15SP5             ansible_host=10.181.3.249
ALNIB-S15SP5             ansible_host=10.181.5.72
APBOGDISTEBOR            ansible_host=10.181.4.239
APBOGDISTEMEV            ansible_host=10.181.5.237
DESPAGEOHYBRIS-QA        ansible_host=10.181.11.170
DIAUT-S15SP5             ansible_host=10.181.8.253
DIPOS-N0                 ansible_host=10.181.5.154
ESCANCODFUENTBOGDIS01    ansible_host=10.181.9.80
FOFON-QA1                ansible_host=10.181.11.130
FOMED-DRP-CLON           ansible_host=10.181.5.184
GEOAPP-CENTRAL-QA        ansible_host=10.181.4.4
GEODB-CENTRAL-QA         ansible_host=10.181.11.114
GEOJENKINS               ansible_host=10.181.4.105
GEOPOSALKAU              ansible_host=10.181.5.69
GEOPOS_CONTLOCAL02       ansible_host=10.181.11.129
GEOPROMONGODB_02         ansible_host=10.181.4.248
MONITORGEOBOGDIS01       ansible_host=10.181.8.221
POS_BACKFAC_PRD          ansible_host=10.181.5.188
RECAL-S15SP5             ansible_host=10.181.4.78
REMOS-N0-S15SP5          ansible_host=10.181.5.209
RES68-S15SP5             ansible_host=10.181.4.79
REVEN-S15SP5             ansible_host=10.181.4.80
SRV-AKBOL-QA             ansible_host=10.181.11.70
SRV-AKVEN-QA             ansible_host=10.181.11.93
SRV-ALINT                ansible_host=10.181.4.39
SRV-ALNIB                ansible_host=10.181.3.223
SRV-DIBAR                ansible_host=10.181.3.220
SRV-DICLA                ansible_host=10.181.4.237
SRV-DILIN                ansible_host=10.181.4.235
SRV-DISCL                ansible_host=10.181.4.86
SRV-DISCO                ansible_host=10.181.3.133
SRV-DISMD                ansible_host=10.181.4.84
SRV-DISML                ansible_host=10.181.3.132
SRV-KALEX                ansible_host=10.181.5.120
SRV-KTINT                ansible_host=10.181.3.124
SRV-RE170                ansible_host=10.181.3.231
SRV-RECAL                ansible_host=10.181.3.232
SRV-REFLO                ansible_host=10.181.3.240
SRV-REPER                ansible_host=10.181.3.230
SRV-REPMD                ansible_host=10.181.4.83
SRV-RES68                ansible_host=10.181.3.233
SRV-REVEN                ansible_host=10.181.3.235
SRV-REVIL                ansible_host=10.181.3.242
SRV-TEDAF                ansible_host=10.181.4.104
TEBOS_GEOPOS             ansible_host=10.181.5.194
TEDAFBOGDIS-QA           ansible_host=10.181.5.181
TEMPL_GEOPOS             ansible_host=10.181.5.211
TERCO-S15SP5             ansible_host=10.181.5.251
TESTGEOBOGDIS02          ansible_host=10.181.11.147
TESTGEOBOGDIS03          ansible_host=10.181.11.148
TESTGEOBOGDIS04          ansible_host=10.181.11.149
TESTGEOBOGDIS1           ansible_host=10.181.11.146
TESTGEODBCENTRAL         ansible_host=10.181.11.97
TESTGEOPROMONGODB        ansible_host=10.181.11.1
TESTGEOPROMONGODB_CLON   ansible_host=10.181.5.203
TESTPOSBACKFAC-QA        ansible_host=10.181.11.31
TEST_GEO_CELULAS-Ansible ansible_host=10.181.8.228
TEST_GEO_CENTRAL_S15SP6_ ansible_host=10.181.11.98

[GEOPOS]
ak170-n0    ansible_host=172.16.10.3
ak170-n1    ansible_host=172.16.10.6
akb30-n0    ansible_host=147.127.110.11
akb30-n1    ansible_host=147.127.110.112
akb68-n0    ansible_host=172.16.11.5
akb68-n1    ansible_host=172.16.11.7
akbar-bk    ansible_host=172.16.107.7
akbar-new   ansible_host=172.16.107.8
akbol-bk    ansible_host=172.16.6.8
akbol-n0    ansible_host=172.16.6.12
akcal-n0    ansible_host=172.16.78.5
akcal-n1    ansible_host=172.16.78.8
akcan-n0    ansible_host=172.16.77.3
akcan-n1    ansible_host=172.16.77.5
akede-n0    ansible_host=172.16.134.5
akede-n1    ansible_host=172.16.134.3
akflo-n0    ansible_host=172.16.124.5
akflo-n1    ansible_host=172.16.124.4
akigp-n0    ansible_host=172.16.91.12
akigp-n1    ansible_host=172.16.91.7
akipi-bk    ansible_host=172.16.8.3
akipi-n0    ansible_host=172.16.8.12
akmos-n0    ansible_host=172.16.79.8
akmos-n1    ansible_host=172.16.79.7
akout-n0    ansible_host=147.127.110.18
akove-new   ansible_host=172.16.4.10
akpas-bk    ansible_host=172.16.7.15
akpas-n0    ansible_host=172.16.7.12
akper-n0    ansible_host=172.16.9.5
akper-n1    ansible_host=172.16.9.3
aksin-bk    ansible_host=172.16.116.80
aksin-new   ansible_host=172.16.116.5
aktuq-n0    ansible_host=172.16.90.12
aktuq-n1    ansible_host=172.16.90.3
akven-n0    ansible_host=172.16.4.5
akven-n1    ansible_host=172.16.4.4
akvil-n0    ansible_host=172.16.3.5
akvil-n1    ansible_host=172.16.3.6
akyop-n0    ansible_host=10.121.0.10
akyop-n1    ansible_host=10.121.0.6
al332-n0    ansible_host=10.76.0.24
al333-n0    ansible_host=10.116.0.3
alace-n0    ansible_host=10.250.3.3
alace-n1    ansible_host=10.250.3.4
alapa-bk    ansible_host=10.173.3.7
alapa-n0    ansible_host=10.173.0.20
alarm-n0    ansible_host=10.189.3.3
alarm-n1    ansible_host=10.189.3.4
alave-n1    ansible_host=10.34.3.3
alave-new   ansible_host=10.34.3.5
alba3-new   ansible_host=10.140.2.6
alba4-new   ansible_host=10.30.3.6
alba5-bk    ansible_host=10.45.3.7
alba5-n0    ansible_host=10.45.3.5
albac-n0    ansible_host=10.118.0.24
albac-n1    ansible_host=10.118.3.4
albar-n0    ansible_host=10.99.0.3
albas-new   ansible_host=10.117.0.11
albe2-n0    ansible_host=10.230.3.5
albel-n0    ansible_host=10.108.2.24
albel-new   ansible_host=10.108.3.87
albn2-n0    ansible_host=10.84.0.100
albn3-new   ansible_host=10.101.3.3
albol-new   ansible_host=10.137.0.50
albu2-bk    ansible_host=10.125.3.8
albu2-n0    ansible_host=10.125.3.3
albuc-n0    ansible_host=10.178.0.30
albuc-n1    ansible_host=10.178.3.4
albuk-n0    ansible_host=10.73.0.3
alca2-n0    ansible_host=10.114.0.3
alca4-new   ansible_host=10.138.3.3
alca5-n0    ansible_host=10.187.3.3
alca5-n1    ansible_host=10.187.3.4
alca6-n0    ansible_host=10.228.3.5
alcal-n0    ansible_host=10.223.3.3
alcen-new   ansible_host=10.35.2.5
alct2-bk    ansible_host=10.139.2.3
alct2-new   ansible_host=10.139.3.3
alcuc-n0    ansible_host=10.172.3.10
alcuc-n1    ansible_host=10.172.3.3
aldie-n0    ansible_host=10.106.3.6
aldie-n1    ansible_host=10.106.3.4
alflo-n1    ansible_host=10.134.3.4
alflo-new   ansible_host=10.134.3.3
aliba-bk    ansible_host=10.144.3.7
aliba-n0    ansible_host=10.144.3.3
alk2m-n0    ansible_host=10.132.0.4
Alk33-n1    ansible_host=10.175.0.27
alk72-n0    ansible_host=10.83.0.3
alka1-n0    ansible_host=10.206.42.6
alka1-n1    ansible_host=10.206.42.7
alkau-new   ansible_host=10.235.3.5
alkun-n0    ansible_host=10.86.3.77
alkun-n2    ansible_host=10.86.0.16
almay-bk    ansible_host=10.87.3.8
almay-n0    ansible_host=10.87.3.3
almo1-n0    ansible_host=10.26.3.6
almol-n0    ansible_host=10.29.3.3
almol-n2    ansible_host=10.29.3.5
alne2-n0    ansible_host=10.240.3.7
alne2-n1    ansible_host=10.240.3.8
alnei-bk    ansible_host=10.149.3.7
alnei-n0    ansible_host=10.149.3.3
alnue-bk    ansible_host=10.49.3.8
alnue-n0    ansible_host=10.49.3.5
alper-n0    ansible_host=10.112.3.3
alper-n1    ansible_host=10.112.3.4
alpie-n1    ansible_host=10.155.3.4
alpie-new   ansible_host=10.155.3.3
alpol-new   ansible_host=10.75.0.3
alpro-new   ansible_host=10.206.0.125
alrio-n0    ansible_host=10.98.0.5
alrio-n1    ansible_host=10.98.3.3
alro1-new   ansible_host=10.157.2.9
alro2-new   ansible_host=10.158.3.77
alro3-n0    ansible_host=10.62.3.2
alrus-new   ansible_host=10.77.0.3
alsan-new   ansible_host=10.52.0.15
alsoa-new   ansible_host=10.142.3.7
alva2-n0    ansible_host=10.156.3.3
alva2-new   ansible_host=10.156.3.7
alval-new   ansible_host=10.113.0.14
alve1-new   ansible_host=172.16.4.7
alven-new   ansible_host=10.81.0.106
alvi2-new   ansible_host=10.150.0.6
alvil-n0    ansible_host=10.251.3.5
foa68-n0    ansible_host=10.229.3.5
fobar       ansible_host=10.133.2.5
fobo1-new   ansible_host=10.97.0.3
focal-new   ansible_host=10.126.3.7
focop-n0    ansible_host=10.242.3.3
fofat-new   ansible_host=10.56.3.3
fofon-n0    ansible_host=10.95.0.3
foita-new   ansible_host=10.119.3.7
fomed-new   ansible_host=10.206.3.2
fomon-n0    ansible_host=10.31.3.7
fopas-n0    ansible_host=172.16.6.25
fovil-new   ansible_host=10.143.3.77
ktame-bk    ansible_host=10.109.3.8
ktame-n0    ansible_host=10.109.0.102
ktark-n0    ansible_host=10.190.3.3
ktark-n1    ansible_host=10.190.3.4
ktb94-n0    ansible_host=10.71.10.27
ktb94-n1    ansible_host=10.71.3.5
ktbar-n0    ansible_host=10.232.3.5
ktbar-n1    ansible_host=10.232.3.6
ktbuc-bk    ansible_host=10.129.3.5
ktbuc-new   ansible_host=10.129.0.8
ktcal-bk    ansible_host=10.48.3.8
ktcal-n0    ansible_host=10.48.3.7
ktchi-bk    ansible_host=10.32.3.8
ktchi-new   ansible_host=10.32.3.5
ktfus-n0    ansible_host=10.203.3.3
ktfus-n1    ansible_host=10.203.3.4
ktgir-n0    ansible_host=10.231.3.5
ktgir-n1    ansible_host=10.231.3.4
ktjul-n0    ansible_host=10.127.0.8
ktjul-n1    ansible_host=10.127.0.7
ktman-n0    ansible_host=10.65.3.5
ktman-n1    ansible_host=10.65.3.9
ktmay-n0    ansible_host=10.104.0.100
ktmay-n1    ansible_host=10.104.3.3
ktmos-bk    ansible_host=10.145.3.7
ktmos-n0    ansible_host=10.145.3.4
ktnqs-n0    ansible_host=10.245.3.3
ktnqs-n1    ansible_host=10.245.3.4
ktpob-bk    ansible_host=10.92.3.4
ktpob-new   ansible_host=10.92.0.24
ktsal-n0    ansible_host=10.91.3.3
ktsal-n2    ansible_host=10.91.3.7
ktsba-n1    ansible_host=10.89.3.3
ktsba-nuevo ansible_host=10.89.0.102
ktsoa-bk    ansible_host=10.46.3.8
ktsoa-new   ansible_host=10.46.3.5
kttes-bk    ansible_host=10.115.3.4
kttes-new   ansible_host=10.115.0.27
kttit-n0    ansible_host=10.122.0.70
kttit-n1    ansible_host=10.122.3.8
kttun-n0    ansible_host=10.90.3.5
kttun-n1    ansible_host=10.90.3.3
ktuno-n0    ansible_host=10.147.3.2
ktuno-n1    ansible_host=10.147.3.3
ktvil-bk    ansible_host=10.151.3.3
ktvil-n0    ansible_host=10.151.3.5
terio-n0    ansible_host=10.40.3.5
ktctg-n0    ansible_host=10.188.3.12
ktctg-n1    ansible_host=10.188.3.10
co100-n0    ansible_host=10.79.3.7

[GEOPOS_MARCAR]
ak170-marcar   ansible_host=10.78.3.27
akb30-marcar   ansible_host=10.51.3.47
akb68-marcar   ansible_host=10.191.3.1
akbar-marcar   ansible_host=10.42.3.20
akbol-marcar   ansible_host=10.131.3.47
akflo-marcar   ansible_host=10.64.3.47
akcan-marcar   ansible_host=10.234.3.40
akcal-marcar   ansible_host=10.124.3.47
akede-marcar   ansible_host=10.110.3.100
akipi-marcar   ansible_host=10.41.6.20
akigp-marcar   ansible_host=10.154.3.47
akpas-marcar   ansible_host=10.141.3.40
akper-marcar   ansible_host=10.53.6.10
aksin-marcar   ansible_host=10.58.3.47
aktuq-marcar   ansible_host=10.55.3.47
akven-marcar   ansible_host=10.81.6.8
akvil-marcar   ansible_host=10.251.3.20
akyop-marcar   ansible_host=10.121.3.47
ktronix-marcar ansible_host=10.191.3.81
akmos-marcar   ansible_host=10.130.3.15