---
- name: Crear usuarios en servidores Linux
  hosts: FSC_TEMP
  become: yes

  vars:
    users:
      - name: rrodriguez
        comment: "Rafael David Rodriguez Barrios"
        home: /home/rrodriguez
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: jmgarcia
        comment: "Jose Miguel Garcia Rosado"
        home: /home/jmgarcia
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: aperez
        comment: "Andres David Perez Garcia"
        home: /home/aperez
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: yguzman
        comment: "Yuxemy Guzman Gonzalez"
        home: /home/yguzman
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: parias
        comment: "Pablo Andres Arias Zapata"
        home: /home/parias
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: jpinilla
        comment: "Javier Pinilla Guzman"
        home: /home/jpinilla
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: nzuluaga
        comment: "Neider Zuluaga Zuluaga"
        home: /home/nzuluaga
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: obenavidez
        comment: "Oscar Flavio Benavidez Jimenez"
        home: /home/obenavidez
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: ramezquita
        comment: "Ronaldo Amezquita Ceron"
        home: /home/ramezquita
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: larias
        comment: "Luis Felipe Arias Martinez"
        home: /home/larias
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: nromero
        comment: "Nibaldo Enrique Romero Sanes"
        home: /home/nromero
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

      - name: obustamante
        comment: "Oscar Javier Bustamante Salgado"
        home: /home/obustamante
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"

  tasks:

    - name: Asegurarse de que los grupos necesarios existen
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ users | map(attribute='group') | unique | list }}"

    - name: Crear usuarios desde la lista
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment | default(omit) }}"
        home: "{{ item.home | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        create_home: yes
        shell: "{{ item.shell | default('/bin/bash') }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ users }}"
      no_log: true

    - name: Forzar cambio de contrase.a al iniciar sesió     ansible.builtin.command: chage -d 0 "{{ item.name }}"
      loop: "{{ users }}"
