---
- name: Crear usuarios en servidores Linux
  hosts: [FSC_TEMP]
  become: yes
  tasks:
    - name: Asegurarse de que el grupo 'soporte' existe
      group:
        name: soporte
        state: present

    - name: Crear los usuarios con descripcion, home, grupo y shell por defecto
      user:
        name: "{{ item.name }}"  # Username
        comment: "{{ item.comment }}" ## Nombre completo del usuario
        home: "/home/{{ item.name }}"  ## home de los usuarios
        group: soporte
        create_home: yes
        shell: /bin/bash
        password: "{{ 'Soporte2025$' | password_hash('sha512') }}" # Contrasena se asigna a los usuarios 
        update_password: on_create
      with_items:
        - { name: "jsanchez", comment: "Juan Pablo Sanchez" }
        - { name: "njaramillo", comment: "Nelson Jaramillo" }
        - { name: "arendon", comment: "Andres Rendon" }
        - { name: "msierra", comment: "Mauricio Sierra" }
        - { name: "oviloria", comment: "Orlando Viloria" }
        - { name: "bescobar", comment: "Brayan Leonardo Escobar" }
        - { name: "ocastellanos", comment: "Oscar Castellanos" }
        - { name: "kacosta", comment: "Kevin Acosta" }
        - { name: "jrueda", comment: "Jorge Rueda" }
        - { name: "rvargas", comment: "Rafael Vargas" }
        - { name: "rlopez", comment: "Rodolfo Lopez" }

    - name: Forzar cambio de contrase.a al iniciar sesion
      command: "chage -d 0 {{ item.name }}"
      with_items:
        - { name: "jsanchez", comment: "Juan Pablo Sanchez" }
        - { name: "njaramillo", comment: "Nelson Jaramillo" }
        - { name: "arendon", comment: "Andres Rendon" }
        - { name: "msierra", comment: "Mauricio Sierra" }
        - { name: "oviloria", comment: "Orlando Viloria" }
        - { name: "bescobar", comment: "Brayan Leonardo Escobar" }
        - { name: "ocastellanos", comment: "Oscar Castellanos" }
        - { name: "kacosta", comment: "Kevin Acosta" }
        - { name: "jrueda", comment: "Jorge Rueda" }
        - { name: "rvargas", comment: "Rafael Vargas" }
        - { name: "rlopez", comment: "Rodolfo Lopez" }

