---
- name: Crear usuarios en servidores Linux
  hosts: FSC_TEMP
  become: yes

  vars:
    users:
      - name: djballesteros
        comment: "Deimer De Jesus Ballesteros Padilla"
        home: /home/djballesteros
        group: soporte
        shell: /bin/bash
        password: "Soporte2025$"
      
    # - name: kacosta  
    #   comment: "Kevin Acosta Canas"
    #    home: /home/kacosta
    #    group: soporte
    #    shell: /bin/bash
    #    password: "Soporte2025$"
    #   
    #  - name: rvargas
    #    comment: "Rafael Vargas Perafan"
    #    home: /home/rvargas
    #    group: soporte
    #    shell: /bin/bash
    #    password: "Soporte2025$"

  tasks:
    - name: Asegurarse de que los grupos necesarios existen
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ users | map(attribute='group') | unique | list }}"

    - name: Crear usuarios desde la lista
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment | default(omit) }}"
        home: "{{ item.home | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        create_home: yes
        shell: "{{ item.shell | default('/bin/bash') }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ users }}"
      no_log: true
    - name: Forzar cambio de contrasena al iniciar sesion
      ansible.builtin.command: chage -d 0 "{{ item.name }}"
      loop: "{{ users }}"

