---
- name: Crear usuario en servidores Linux
  hosts:  [FSC_MOVILVENTAS]
  become: yes
  tasks:
    - name: Asegurarse de que el grupo 'support' existe
      group:
        name: support 
        state: present

    - name: Crear el usuario  con descripcion, home, grupo y shell por defecto
      user:
        name: depmov
        comment: "usurio devops"
        home: /home/depmov
        group: support
        create_home: yes
        shell: /bin/bash
        password: "{{ 'Soporte2025$' | password_hash('sha512') }}"
        update_password: on_create

    - name: Forzar cambio de contraseña al iniciar sesion    
      command: chage -d 0 depmov
