---
- name: Crear usuarios en servidores Linux
  hosts: [FSC_TEMP]
  become: yes
  tasks:
    - name: Asegurarse de que el grupo 'soporte' existe
      group:
        name: soporte
        state: present

    - name: Crear los usuarios con descripcion, home, grupo y shell por defecto
      user:
        name: "{{ item.name }}"  # Username
        comment: "{{ item.comment }}" ## Nombre completo del usuario
        home: "/home/{{ item.name }}"  ## home de los usuarios
        group: soporte
        create_home: yes
        shell: /bin/bash
        password: "{{ 'Soporte2025$' | password_hash('sha512') }}" # Contrasena se asigna a los usuarios
        update_password: on_create
      with_items:
        - { name: "abarbosa", comment: "Alexander Barbosa" }
        - { name: "acuevas", comment: "Andres Cuevas" }
        - { name: "arodriguez", comment: "Alexander Rodriguez" }
        - { name: "aromero", comment: "Alexis Romero" }
        - { name: "bmarin", comment: "brandon marin" }
        - { name: "calonso", comment: "Christian German Alonso Segura" }
        - { name: "clozano", comment: "Carlos Adolfo Lozano Rodriguez" }
        - { name: "cperez", comment: "Camilo Perez" }
        - { name: "cpineda", comment: "Carlos Augusto Pineda Roldan" }
        - { name: "cserrano", comment: "Cesar David Serrano" }
        - { name: "csotomonte", comment: "Cesar Alberto Sotomonte" }
        - { name: "dcaballero", comment: "Dagoberto Layton Caballero" }
        - { name: "dforerof", comment: "daniel forero" }
        - { name: "ebernal", comment: "Eder Bernal" }
        - { name: "eramirez", comment: "Edgar Ramirez" }
        - { name: "facosta", comment: "Fabian Elias Acosta Fajardo" }
        - { name: "frodriguez", comment: "Fabian Rodriguez" }
        - { name: "iardila", comment: "Ivonne Ardila Prada" }
        - { name: "jcampo", comment: "Juan Sebastian Campo Herrera" }
        - { name: "jjimenez", comment: "Jair Jimenez Guevara" }
        - { name: "mbernal", comment: "Myrian Camacho Bernal" }
        - { name: "mrivas", comment: "Michael Rene Rivas Reyes" }
        - { name: "nmachado", comment: "Nestor Machado" }
        - { name: "oviloria", comment: "Orlando Viloria" }
        - { name: "ptocarruncho", comment: "Paula Tocarruncho" }
        - { name: "rlopez", comment: "Rodolfo Lopez" }
        - { name: "rmoreno", comment: "Ricardo Humberto Moreno Melo" }
        - { name: "wfranco", comment: "Wilmar Franco" }
        - { name: "yureche", comment: "Yahir Ureche" }
        - { name: "jsuarez", comment: "Jairo Suarez" }
        - { name: "gochoa", comment: "German Alberto Ochoa" }
        - { name: "izapata", comment: "Ivan Camilo Zapata" }

    - name: Forzar cambio de contrase.a al iniciar sesion
      command: "chage -d 0 {{ item.name }}"
      with_items:
        - { name: "abarbosa", comment: "Alexander Barbosa" }
        - { name: "acuevas", comment: "Andres Cuevas" }
        - { name: "arodriguez", comment: "Alexander Rodriguez" }
        - { name: "aromero", comment: "Alexis Romero" }
        - { name: "bmarin", comment: "brandon marin" }
        - { name: "calonso", comment: "Christian German Alonso Segura" }
        - { name: "clozano", comment: "Carlos Adolfo Lozano Rodriguez" }
        - { name: "cperez", comment: "Camilo Perez" }
        - { name: "cpineda", comment: "Carlos Augusto Pineda Roldan" }
        - { name: "cserrano", comment: "Cesar David Serrano" }
        - { name: "csotomonte", comment: "Cesar Alberto Sotomonte" }
        - { name: "dcaballero", comment: "Dagoberto Layton Caballero" }
        - { name: "dforerof", comment: "daniel forero" }
        - { name: "ebernal", comment: "Eder Bernal" }
        - { name: "eramirez", comment: "Edgar Ramirez" }
        - { name: "facosta", comment: "Fabian Elias Acosta Fajardo" }
        - { name: "frodriguez", comment: "Fabian Rodriguez" }
        - { name: "iardila", comment: "Ivonne Ardila Prada" }
        - { name: "jcampo", comment: "Juan Sebastian Campo Herrera" }
        - { name: "jjimenez", comment: "Jair Jimenez Guevara" }
        - { name: "mbernal", comment: "Myrian Camacho Bernal" }
        - { name: "mrivas", comment: "Michael Rene Rivas Reyes" }
        - { name: "nmachado", comment: "Nestor Machado" }
        - { name: "oviloria", comment: "Orlando Viloria" }
        - { name: "ptocarruncho", comment: "Paula Tocarruncho" }
        - { name: "rlopez", comment: "Rodolfo Lopez" }
        - { name: "rmoreno", comment: "Ricardo Humberto Moreno Melo" }
        - { name: "wfranco", comment: "Wilmar Franco" }
        - { name: "yureche", comment: "Yahir Ureche" }
        - { name: "jsuarez", comment: "Jairo Suarez" }
        - { name: "gochoa", comment: "German Alberto Ochoa" }
        - { name: "izapata", comment: "Ivan Camilo Zapata" }


