---
- name: Crear usuario en servidores Linux
  hosts: GEOPOS_FSC_PPAL_ALKNORTE 
  become: yes
  tasks:
    - name: Asegurarse de que el grupo 'soporte' existe
      group:
        name: soporte
        state: present

    - name: Crear el usuario  con descripcion, home, grupo y shell por defecto
      user:
        name: cvillareal
        comment: "cristhian camilo villareal"
        home: /home/cvillareal
        group: soporte
        create_home: yes
        shell: /bin/bash
        password: "{{ 'Soporte2025$' | password_hash('sha512') }}"
        update_password: on_create

    - name: Forzar cambio de contraseña al iniciar sesion    
      command: chage -d 0 cvillareal
