---
- name: Eliminar un usuario y su directorio home
  hosts: [GEOPOS_FSC_PPAL_ALKNORTE]
  become: true
  tasks:
    - name: Asegurarse de que el usuario existe
      user:
        name: "{{ nombre_usuario }}"
        state: present
      register: usuario_existe

    - name: Eliminar el usuario
      user:
        name: "{{ nombre_usuario }}"
        state: absent
        remove: yes
      when: usuario_existe.changed

    - name: Eliminar el directorio home del usuario (si existe)
      file:
        path: "/home/{{ nombre_usuario }}"
        state: absent
      when: usuario_existe.changed
